In [2]:
# pada
import pandas as pd 
import numpy as np

In [2]:
#import the pandas library and aliasing as pd
s = pd.Series()
print(s)

Series([], dtype: float64)


In [6]:
#import the pandas library and aliasing as pd
data = np.array(['a','b','c','d'])
s = pd.Series(data)
print(s)

0    a
1    b
2    c
3    d
dtype: object


In [18]:
#import the pandas library and aliasing as pd
data = np.array(['a','b','c'])
s = pd.Series(data,index=[100,101,102])
print(s)

100    a
101    b
102    c
dtype: object


In [20]:
#import the pandas library and aliasing as pd
data = {'a':10.,'b':11.,'c':12.}
s = pd.Series(data)
print(s)

a    10.0
b    11.0
c    12.0
dtype: float64


In [22]:
data = [[1,2],[6,7]]
df = pd.DataFrame(data,columns=["column1", "column2"])
df.head()

column1  column2
0        1        2
1        6        7

In [24]:
data =[['Alex', 10],['Bob',12],['Clark',13]]
df = pd.DataFrame(data)
df.head()

0   1
0   Alex  10
1    Bob  12
2  Clark  13

In [26]:
data = {'Name':['Tom', 'Jack', 'Steve', 'Ricky'],'Age':[28,34,29,42]}
df = pd.DataFrame(data, index=['rank1','rank2','rank3','rank4'])
df.head()

Name  Age
rank1    Tom   28
rank2   Jack   34
rank3  Steve   29
rank4  Ricky   42

In [27]:
data = [{'a': 1, 'b': 2},{'a': 5, 'b': 10, 'c': 20}]
df = pd.DataFrame(data, index=['first', 'second'])
df.head()

a   b     c
first   1   2   NaN
second  5  10  20.0

In [28]:
d = [[1,2,3,4],[2,3,5,6]]
s = pd.DataFrame(d, columns=['column1', 'column2', 'column3', 'column4'])
print(s.head())

print("\n")
print(s['column3'])

   column1  column2  column3  column4
0        1        2        3        4
1        2        3        5        6


In [29]:
x = [[1,3],[2,4]]
s = pd.DataFrame(x,columns=['column1','column2'])
print(s.head())

print("\n")
print(s["column2"])

   column1  column2
0        1        3
1        2        4


0    3
1    4
Name: column2, dtype: int64


In [34]:
x = np.random.randn(40)
x = x.reshape((-1,5))
s = pd.DataFrame(x)
s.head(7)


0         1         2         3         4
0  1.227673  0.824689 -1.116908  1.517800 -0.426829
1  0.935560  1.573277 -0.795913 -0.189699  0.719915
2 -0.131427  0.099829 -0.007959  0.938956  0.096602
3  1.123027  1.037674  0.435358 -0.744549  1.932087
4  0.305845  1.159053 -1.157912 -0.884367 -0.398298
5 -1.152445  0.256593 -0.702228 -0.242686  0.755474
6  1.573861 -1.731268 -1.170019 -0.368251  2.048130

In [35]:
x = np.random.randn(40)
x = x.reshape((-1,5))
s = pd.DataFrame(x)
s.tail(2)

0         1         2         3         4
6 -1.007757 -0.391043  0.697545  0.978686  0.568443
7 -0.318384 -1.388905 -0.706748  1.040009 -1.088904

In [37]:
x = np.random.randn(30)
x = x.reshape((-1,5))

s = pd.DataFrame(x)
print(s)
print("\n\n")
print(s.T)

          0         1         2         3         4
0 -0.105496  0.374848 -0.544530  1.117713 -0.511513
1  0.356186 -1.080410 -0.049642 -0.043163 -0.731498
2  0.203524  0.955148  0.122235 -1.174489  0.035424
3  0.343112 -0.193178 -0.264112 -1.119586  0.313100
4 -1.546517  0.873277 -0.593549 -0.616396  1.126518
5 -0.784790 -0.338817  1.289657 -1.381403 -0.764034



          0         1         2         3         4         5
0 -0.105496  0.356186  0.203524  0.343112 -1.546517 -0.784790
1  0.374848 -1.080410  0.955148 -0.193178  0.873277 -0.338817
2 -0.544530 -0.049642  0.122235 -0.264112 -0.593549  1.289657
3  1.117713 -0.043163 -1.174489 -1.119586 -0.616396 -1.381403
4 -0.511513 -0.731498  0.035424  0.313100  1.126518 -0.764034


In [42]:
x = np.random.randn(30)
x = x.reshape((-1,5))
s = pd.DataFrame(x)
print(s)
print("\n\n")
print(s.dtypes)
print("\n",s.shape)
print("\n",s.size)
print("\n",s.values)

          0         1         2         3         4
0  0.045091 -0.048637  1.146810 -0.954356  0.723190
1  1.196742 -0.568056  2.383291 -0.142784  0.611620
2  2.143977 -0.623572  1.973072 -0.520841 -0.168778
3 -0.663318  0.656545 -1.970472  0.389672  0.398103
4  0.361645  0.595457 -1.054627  0.068696  2.919998
5  0.974186  0.321653  0.280873  1.344896 -0.752252



0    float64
1    float64
2    float64
3    float64
4    float64
dtype: object

 (6, 5)

 30

 [[ 0.04509141 -0.0486374   1.1468098  -0.95435643  0.72318964]
 [ 1.19674191 -0.56805645  2.3832911  -0.14278392  0.6116204 ]
 [ 2.14397689 -0.62357249  1.9730719  -0.52084104 -0.16877824]
 [-0.66331825  0.65654542 -1.97047205  0.38967192  0.39810328]
 [ 0.3616452   0.59545657 -1.05462688  0.06869634  2.91999842]
 [ 0.97418624  0.32165265  0.28087259  1.34489564 -0.75225207]]


In [45]:
x = np.random.randn(30)
x = x.reshape((-1,5))

s = pd.DataFrame(x)
print("\n",s)
print("\n",s.sum(axis=0))
print("\n",s.mean(axis=1))
print("\n",s.std())
print("\n",s.min().max())



           0         1         2         3         4
0 -0.378904 -0.286969 -0.213992  0.016173 -0.338257
1 -0.026960  1.511040 -0.986570  0.072654  0.344683
2  0.861868  0.402938  1.471075 -0.403618  1.418308
3  0.879987  0.131404 -0.146692  0.136261  0.496693
4  0.543656  0.569741  0.313606  0.139961  0.732282
5  0.898172  0.451146 -1.490933 -0.406567 -0.858220

 0    2.777820
1    2.779299
2   -1.053506
3   -0.445135
4    1.795489
dtype: float64

 0   -0.240390
1    0.182969
2    0.750114
3    0.299531
4    0.459849
5   -0.281280
dtype: float64

 0    0.543639
1    0.597652
2    1.033532
3    0.260337
4    0.803369
dtype: float64

 -0.28696851114582644


In [48]:
def adder(x1, x2):
    return x1+x2
x = pd.DataFrame(np.random.randn(7,4))
print(x)
print("\n\n")
print(x.pipe(adder,10))
print(x)

          0         1         2         3
0  0.908426 -0.791481 -0.804089  1.178486
1  0.268892 -0.342063  1.100824 -0.360982
2  0.561572 -0.018451  0.110412  1.254153
3 -1.059808  0.728562  1.337483 -0.058548
4  0.820889  0.628922  0.291417 -1.335718
5 -0.047730  0.554819  1.483084  0.768356
6  1.082191  1.231592  0.075415 -0.773193



           0          1          2          3
0  10.908426   9.208519   9.195911  11.178486
1  10.268892   9.657937  11.100824   9.639018
2  10.561572   9.981549  10.110412  11.254153
3   8.940192  10.728562  11.337483   9.941452
4  10.820889  10.628922  10.291417   8.664282
5   9.952270  10.554819  11.483084  10.768356
6  11.082191  11.231592  10.075415   9.226807
          0         1         2         3
0  0.908426 -0.791481 -0.804089  1.178486
1  0.268892 -0.342063  1.100824 -0.360982
2  0.561572 -0.018451  0.110412  1.254153
3 -1.059808  0.728562  1.337483 -0.058548
4  0.820889  0.628922  0.291417 -1.335718
5 -0.047730  0.554819  1.483084  0.768356

In [52]:
x = pd.DataFrame(np.random.randn(7,4))
print(x)

def add4(x1):
    return x1 + 20
print(x.apply(add4))

          0         1         2         3
0  0.248495 -1.248656  1.262526 -0.005347
1  0.343777 -0.553954  1.166358 -0.208976
2 -0.386201 -1.309358 -0.409941  1.195270
3 -0.779155 -0.955748 -1.287416 -0.906948
4 -0.843552  0.122535  0.212251 -0.114427
5  0.307569 -0.501130 -0.256146 -1.611103
6  1.350487  0.067052 -0.694802 -0.143870
           0          1          2          3
0  20.248495  18.751344  21.262526  19.994653
1  20.343777  19.446046  21.166358  19.791024
2  19.613799  18.690642  19.590059  21.195270
3  19.220845  19.044252  18.712584  19.093052
4  19.156448  20.122535  20.212251  19.885573
5  20.307569  19.498870  19.743854  18.388897
6  21.350487  20.067052  19.305198  19.856130


In [53]:
x = pd.DataFrame(np.random.randn(7,4))
print(x)
print("\n\n\n", x.apply(np.mean,axis = 1))

          0         1         2         3
0 -0.220670 -1.202914 -0.795292  2.132608
1  1.082589 -2.260037  0.372638  1.328492
2  1.891633  0.643914 -1.642036  0.517401
3  0.446476 -0.199605  0.584092  0.651621
4 -0.124576  0.830372  0.828184 -0.670269
5 -0.215257  0.224372  0.420318 -0.163279
6  0.800213  0.775182  0.378120  0.333228



 0   -0.021567
1    0.130920
2    0.352728
3    0.370646
4    0.215928
5    0.066538
6    0.571686
dtype: float64


In [54]:
x = pd.DataFrame(np.random.randn(7,4))
print(x)

print("\n\n")
print(x[1].map(lambda x:x*100))

          0         1         2         3
0  0.026009  0.064812  1.213882 -0.332693
1  0.710498 -0.467922 -0.026286 -0.984056
2 -0.135065 -1.481868 -0.703742 -0.508585
3  0.960762  0.912436  1.514997  2.058607
4  0.357189  0.090772  0.474370  1.191556
5  0.714153 -1.725191 -0.231940 -1.127141
6 -0.469745 -1.547166 -1.135349 -0.182946



0      6.481225
1    -46.792219
2   -148.186753
3     91.243608
4      9.077242
5   -172.519122
6   -154.716553
Name: 1, dtype: float64


In [55]:
x = pd.DataFrame(np.random.randn(7,4), columns=['c1', 'c2', 'c3', 'c4'])
print(x)
print("\n\n")
print(x[['c2','c4']])

         c1        c2        c3        c4
0 -0.620297  1.455638  0.498932  1.201080
1  0.380398  0.394648  1.293139  0.486742
2  0.676837 -1.750858  1.570362  0.368706
3  1.326565 -2.183365 -0.059484  2.739738
4 -0.574777 -0.042412  0.364325 -0.150396
5  1.629050 -0.740567  1.292301  0.420871
6 -0.507121  1.522737  0.265090 -0.164923



         c2        c4
0  1.455638  1.201080
1  0.394648  0.486742
2 -1.750858  0.368706
3 -2.183365  2.739738
4 -0.042412 -0.150396
5 -0.740567  0.420871
6  1.522737 -0.164923


In [56]:
x = pd.DataFrame(np.random.randn(7,4), columns=['c1', 'c2', 'c3', 'c4'])
print(x)
print("\n\n")
for key, value in x.iteritems():
    print(key, value)

         c1        c2        c3        c4
0 -2.335038  0.893008 -0.355276  0.809923
1  0.129669  0.299441  1.431530 -0.307549
2  2.134996  1.631227  1.934791  0.915731
3 -0.478048 -1.279862  1.191271 -0.492750
4  1.561043 -0.787364  1.450543 -0.166855
5 -1.064510  2.454824 -0.053860  0.182089
6  0.140073  0.092393 -0.384056  1.373350



c1 0   -2.335038
1    0.129669
2    2.134996
3   -0.478048
4    1.561043
5   -1.064510
6    0.140073
Name: c1, dtype: float64
c2 0    0.893008
1    0.299441
2    1.631227
3   -1.279862
4   -0.787364
5    2.454824
6    0.092393
Name: c2, dtype: float64
c3 0   -0.355276
1    1.431530
2    1.934791
3    1.191271
4    1.450543
5   -0.053860
6   -0.384056
Name: c3, dtype: float64
c4 0    0.809923
1   -0.307549
2    0.915731
3   -0.492750
4   -0.166855
5    0.182089
6    1.373350
Name: c4, dtype: float64


In [57]:
x = pd.DataFrame(np.random.randn(7,4), columns=['c1', 'c2', 'c3', 'c4'])
print(x)
print("\n\n")
for index, row in x.iterrows():
    print(index, row)


         c1        c2        c3        c4
0 -0.321573  0.388257 -1.139018 -1.477471
1  0.882881  0.726899  0.306128 -2.476709
2 -0.119823 -0.846500 -0.761634 -0.029435
3 -0.913942 -1.571047 -0.246957  0.202452
4  1.087195  2.008650  0.746206  0.033222
5  0.669673  0.555070 -0.881472 -1.173880
6  1.908878 -1.305311 -0.976019 -0.980194



0 c1   -0.321573
c2    0.388257
c3   -1.139018
c4   -1.477471
Name: 0, dtype: float64
1 c1    0.882881
c2    0.726899
c3    0.306128
c4   -2.476709
Name: 1, dtype: float64
2 c1   -0.119823
c2   -0.846500
c3   -0.761634
c4   -0.029435
Name: 2, dtype: float64
3 c1   -0.913942
c2   -1.571047
c3   -0.246957
c4    0.202452
Name: 3, dtype: float64
4 c1    1.087195
c2    2.008650
c3    0.746206
c4    0.033222
Name: 4, dtype: float64
5 c1    0.669673
c2    0.555070
c3   -0.881472
c4   -1.173880
Name: 5, dtype: float64
6 c1    1.908878
c2   -1.305311
c3   -0.976019
c4   -0.980194
Name: 6, dtype: float64


# May-2,2019.

In [28]:
x = pd.DataFrame(np.random.randn(7,4), columns=['c1', 'c2', 'c3', 'c4'])
print(x)
print("\n\n")
print(x.iteritems())

for key, value in x.iteritems():
    print("key = ",key)
    print("value = \n", value)

         c1        c2        c3        c4
0 -0.538859 -1.444580 -0.610499  1.359819
1 -0.984772  0.124769 -0.501471  1.230928
2 -0.675208 -1.160754 -0.488820  1.527237
3 -0.044108 -1.102328  0.465678  2.180430
4  0.485248  0.309705  1.013740  1.103797
5  0.082830 -0.661412  0.893627 -0.309491
6  0.374706  1.155776 -1.744727  0.186464



<generator object DataFrame.iteritems at 0x00000274B0B2EF48>
key =  c1
value = 
 0   -0.538859
1   -0.984772
2   -0.675208
3   -0.044108
4    0.485248
5    0.082830
6    0.374706
Name: c1, dtype: float64
key =  c2
value = 
 0   -1.444580
1    0.124769
2   -1.160754
3   -1.102328
4    0.309705
5   -0.661412
6    1.155776
Name: c2, dtype: float64
key =  c3
value = 
 0   -0.610499
1   -0.501471
2   -0.488820
3    0.465678
4    1.013740
5    0.893627
6   -1.744727
Name: c3, dtype: float64
key =  c4
value = 
 0    1.359819
1    1.230928
2    1.527237
3    2.180430
4    1.103797
5   -0.309491
6    0.186464
Name: c4, dtype: float64


In [8]:
x = pd.DataFrame(np.random.randn(7,4), columns=['c1', 'c2', 'c3', 'c4'])
print(x)
print("\n\n")
print(x.iteritems())

for ind, row in x.iterrows():
    print("index = ", ind)
    print("row = \n", row)

         c1        c2        c3        c4
0 -0.806319  0.180501  1.068731  0.143848
1  1.525639  0.639167  0.401761  0.786121
2 -0.111505  0.099166 -0.313765 -1.226550
3  1.343441  0.922185 -2.210424  0.501831
4  0.035889  1.048407  0.613465  0.102926
5 -1.723978 -1.622568 -1.269175 -0.076283
6  2.071009  0.110023  1.328730  0.408752



<generator object DataFrame.iteritems at 0x00000274B0B2EED0>
index =  0
row = 
 c1   -0.806319
c2    0.180501
c3    1.068731
c4    0.143848
Name: 0, dtype: float64
index =  1
row = 
 c1    1.525639
c2    0.639167
c3    0.401761
c4    0.786121
Name: 1, dtype: float64
index =  2
row = 
 c1   -0.111505
c2    0.099166
c3   -0.313765
c4   -1.226550
Name: 2, dtype: float64
index =  3
row = 
 c1    1.343441
c2    0.922185
c3   -2.210424
c4    0.501831
Name: 3, dtype: float64
index =  4
row = 
 c1    0.035889
c2    1.048407
c3    0.613465
c4    0.102926
Name: 4, dtype: float64
index =  5
row = 
 c1   -1.723978
c2   -1.622568
c3   -1.269175
c4   -0.076283
Name: 

In [11]:
unsorted_df=pd.DataFrame(np.random.randn(10,2),index=[1,4,6,2,3,5,9,8,0,7],columns=['col2','col1'])
print(unsorted_df)

print("\n\n")
print(unsorted_df.sort_index())

       col2      col1
1  0.840425  0.765031
4  1.331319  0.036303
6 -2.068184 -1.356613
2  0.666356  0.075084
3  0.377326 -1.396498
5 -0.153159 -0.792001
9 -0.079265  2.498028
8  1.074894 -0.173111
0  0.828193 -0.667614
7 -2.025760  1.351399



       col2      col1
0  0.828193 -0.667614
1  0.840425  0.765031
2  0.666356  0.075084
3  0.377326 -1.396498
4  1.331319  0.036303
5 -0.153159 -0.792001
6 -2.068184 -1.356613
7 -2.025760  1.351399
8  1.074894 -0.173111
9 -0.079265  2.498028


In [12]:
unsorted_df=pd.DataFrame(np.random.randn(10,2),index=[1,4,6,2,3,5,9,8,0,7],columns=['col2','col1'])
print(unsorted_df)

print("\n\n")
print(unsorted_df.sort_index(axis=1))

       col2      col1
1 -0.969715  1.069143
4  2.244657 -0.759528
6 -2.231657 -0.519470
2  0.243583 -0.663343
3  2.797747 -0.982444
5 -0.433958  0.921443
9  0.758574 -0.140077
8 -1.703743  0.376428
0 -0.066841  0.648768
7  0.245880 -1.231699



       col1      col2
1  1.069143 -0.969715
4 -0.759528  2.244657
6 -0.519470 -2.231657
2 -0.663343  0.243583
3 -0.982444  2.797747
5  0.921443 -0.433958
9 -0.140077  0.758574
8  0.376428 -1.703743
0  0.648768 -0.066841
7 -1.231699  0.245880


In [13]:
unsorted_df=pd.DataFrame(np.random.randn(10,2),index=[1,4,6,2,3,5,9,8,0,7],columns=['col2','col1'])
print(unsorted_df)

print("\n\n")
print(unsorted_df.sort_values(by='col1', ascending=False))

       col2      col1
1 -0.449534  0.874430
4  1.284515 -1.045812
6  0.777535 -0.158216
2 -1.425040  1.078284
3  0.585979  0.112879
5 -1.016149  1.731430
9 -0.741615 -1.486535
8 -0.899201 -0.771422
0 -0.422517  0.733304
7 -0.913444  2.224308



       col2      col1
7 -0.913444  2.224308
5 -1.016149  1.731430
2 -1.425040  1.078284
1 -0.449534  0.874430
0 -0.422517  0.733304
3  0.585979  0.112879
6  0.777535 -0.158216
8 -0.899201 -0.771422
4  1.284515 -1.045812
9 -0.741615 -1.486535


In [14]:
s = pd.DataFrame(['Tom', 'William Rick', 'John', 'Alber@t', np.nan, '1234','SteveSmith'])

print(s)
print("\n\n")
print(s[0].str.len())

              0
0           Tom
1  William Rick
2          John
3       Alber@t
4           NaN
5          1234
6    SteveSmith



0     3.0
1    12.0
2     4.0
3     7.0
4     NaN
5     4.0
6    10.0
Name: 0, dtype: float64


In [29]:
df=pd.DataFrame(np.random.randn(10,2), columns=['col2','col1'])
print(df)

print("\n\n",df['col1'])
print("\n\n", df[2:5])

       col2      col1
0  0.132994  0.625637
1  0.427874 -0.701517
2 -0.530314  1.468782
3  2.384653  0.263340
4  0.437788 -1.333279
5 -0.997738  0.132296
6 -1.122058 -0.255081
7 -0.617333  0.310417
8 -1.322646  0.837961
9 -0.421410  1.186170


 0    0.625637
1   -0.701517
2    1.468782
3    0.263340
4   -1.333279
5    0.132296
6   -0.255081
7    0.310417
8    0.837961
9    1.186170
Name: col1, dtype: float64


        col2      col1
2 -0.530314  1.468782
3  2.384653  0.263340
4  0.437788 -1.333279


In [18]:
#location indexing
df=pd.DataFrame(np.random.randn(10,3), columns=['col1','col2', 'col3'])
print(df)

print("\n\n")
print(df.loc[2:5, ['col1', 'col3']])

       col1      col2      col3
0 -0.195338 -0.201199  0.415430
1  1.293073  1.020594 -0.234682
2 -0.477974 -2.026056  0.893765
3  1.587481  0.829140 -0.908536
4  0.344278 -1.082662 -0.065563
5 -0.936843  1.955629 -0.052156
6  1.048677 -0.660001 -0.107714
7 -0.531986 -1.554284  1.050597
8 -1.933014  1.230742 -1.425414
9  1.802074 -0.579484  0.615911



       col1      col3
2 -0.477974  0.893765
3  1.587481 -0.908536
4  0.344278 -0.065563
5 -0.936843 -0.052156


In [19]:
#integer indexing
df=pd.DataFrame(np.random.randn(10,3), columns=['col1','col2', 'col3'])
print(df)

print("\n\n")
print(df.iloc[3:-1, ::2])

       col1      col2      col3
0 -1.118474 -0.251925  0.558683
1 -0.442855 -0.998445 -1.105560
2 -0.856883 -0.421247  0.068603
3 -0.171509 -1.540222  0.584073
4 -1.246339  0.773597 -0.113462
5 -1.382177  1.302225  0.862319
6 -0.371378  0.297826  0.920287
7 -1.207607  0.738468  1.700738
8 -0.577968 -0.989977  1.231978
9  1.551422  0.240808  0.689801



       col1      col3
3 -0.171509  0.584073
4 -1.246339 -0.113462
5 -1.382177  0.862319
6 -0.371378  0.920287
7 -1.207607  1.700738
8 -0.577968  1.231978


In [20]:
# used loc and iloc both. 
df=pd.DataFrame(np.random.randn(10,3), columns=['col1','col2', 'col3'])
print(df)

print("\n\n")
print(df.ix[3:])

       col1      col2      col3
0 -0.281071  0.114729 -1.186684
1 -0.573996  2.093587 -0.913704
2 -3.027674 -0.742838 -0.369472
3 -0.083709  1.019926  2.310367
4  0.412188 -0.964671 -0.097254
5 -1.602799  1.800159  0.328608
6  0.733568  1.024757  0.360361
7 -0.505976 -0.321674  0.670633
8 -1.180572  1.827027 -0.398540
9 -1.773250  0.212460 -1.218741



       col1      col2      col3
3 -0.083709  1.019926  2.310367
4  0.412188 -0.964671 -0.097254
5 -1.602799  1.800159  0.328608
6  0.733568  1.024757  0.360361
7 -0.505976 -0.321674  0.670633
8 -1.180572  1.827027 -0.398540
9 -1.773250  0.212460 -1.218741


C:\Users\hp\Anaconda3\New folder\lib\site-packages\ipykernel_launcher.py:5: DeprecationWarning: 
.ix is deprecated. Please use
.loc for label based indexing or
.iloc for positional indexing

See the documentation here:
http://pandas.pydata.org/pandas-docs/stable/indexing.html#ix-indexer-is-deprecated
  """


In [21]:
df=pd.DataFrame(np.random.randn(10,3), columns=['col1','col2', 'col3'])
print(df)

print("\n\n")

print(df['col2'], "\n\n")

print(df.col2)

       col1      col2      col3
0 -0.997386 -0.750813 -1.308879
1  0.672920  1.260031 -0.836720
2  0.025755  0.889626  0.763246
3 -0.326277  0.542438 -0.361950
4 -0.023533  0.570906 -1.099670
5 -0.807757  0.901423  0.348218
6  1.300548 -0.342408 -0.630200
7  0.413314 -0.494369 -0.566006
8  1.125187 -0.415550  2.271676
9 -0.547388  1.405805 -0.455916



0   -0.750813
1    1.260031
2    0.889626
3    0.542438
4    0.570906
5    0.901423
6   -0.342408
7   -0.494369
8   -0.415550
9    1.405805
Name: col2, dtype: float64 


0   -0.750813
1    1.260031
2    0.889626
3    0.542438
4    0.570906
5    0.901423
6   -0.342408
7   -0.494369
8   -0.415550
9    1.405805
Name: col2, dtype: float64


In [22]:
df=pd.DataFrame(np.random.randn(10,3), columns=['col1','col2', 'col3'])
print(df)

df.col2 = df.col2 * 100

print("\n\n", df)

       col1      col2      col3
0  0.628256 -1.156729  0.962723
1  0.344338 -2.054508  0.957612
2 -0.031447  1.775773  0.553630
3  0.283310 -0.042293 -1.326530
4  0.974519  0.903885  0.786410
5 -1.252935 -0.077845  0.196364
6  2.015876  1.121039 -0.359756
7 -0.185871  0.104420 -0.668665
8  0.484397 -1.985520 -1.109935
9 -0.338196  1.531319 -0.401585


        col1        col2      col3
0  0.628256 -115.672902  0.962723
1  0.344338 -205.450807  0.957612
2 -0.031447  177.577263  0.553630
3  0.283310   -4.229319 -1.326530
4  0.974519   90.388546  0.786410
5 -1.252935   -7.784469  0.196364
6  2.015876  112.103924 -0.359756
7 -0.185871   10.442034 -0.668665
8  0.484397 -198.552002 -1.109935
9 -0.338196  153.131908 -0.401585


In [23]:
# data corrleation
df=pd.DataFrame(np.random.randn(10,3), columns=['col1','col2', 'col3'])
print(df)

print("\n")
print(df.corr())

       col1      col2      col3
0  0.657985 -0.699967 -1.439413
1  0.006209  1.222225  1.317719
2  0.199645 -0.526183  1.141379
3 -1.320058 -0.155896  1.195336
4 -0.552005  0.455903 -0.817122
5  1.456728 -0.389698 -0.202152
6  1.230635  0.885545 -0.326770
7 -1.004810  0.062925 -0.263579
8 -0.121673  0.803806 -0.128993
9 -0.342840  0.896215 -1.388834


          col1      col2      col3
col1  1.000000 -0.108689 -0.213681
col2 -0.108689  1.000000  0.018540
col3 -0.213681  0.018540  1.000000


In [24]:
# Data Conversition.
dic  = {'x':[3,4,5], 'y':[10,11,12]}
df = pd.DataFrame(dic)

print(df)

print("\n\n", df.cov())

   x   y
0  3  10
1  4  11
2  5  12


      x    y
x  1.0  1.0
y  1.0  1.0


In [27]:
dic  = {'x':[3,4,5], 'y':[10,11,12]}
df = pd.DataFrame(dic)

print(df)

print("\n\n", df.corr())

   x   y
0  3  10
1  4  11
2  5  12


      x    y
x  1.0  1.0
y  1.0  1.0


In [10]:
df=pd.DataFrame(np.random.randn(10,5), columns=['A','B','C','D','E'])
print(df)

print(df.loc[2:6, ['A', 'B']])

print("\n\n")

print(df.corr())

          A         B         C         D         E
0  1.035608 -0.142526  0.513129  0.051211 -0.371688
1 -0.041986 -0.006720 -2.034566 -0.323791 -2.031305
2 -1.675308 -1.618710 -0.942212  0.205755 -0.597546
3  1.697793  0.656652 -1.370954  1.215914  0.598165
4  1.515063 -1.036313  1.394797 -1.727638 -0.410980
5  0.906462  0.002080  0.381601 -0.187833  0.719469
6 -0.549106 -0.151909 -0.204846  1.876942  0.873264
7  1.159137 -1.689207 -0.292726  0.590547  1.064241
8 -0.890860  1.042741  1.276871  0.575183 -0.857771
9  0.303494  1.422860  1.517816  0.085885 -0.659034
          A         B
2 -1.675308 -1.618710
3  1.697793  0.656652
4  1.515063 -1.036313
5  0.906462  0.002080
6 -0.549106 -0.151909



          A         B         C         D         E
A  1.000000  0.025223  0.109691 -0.274811  0.374289
B  0.025223  1.000000  0.276376  0.225988 -0.236437
C  0.109691  0.276376  1.000000 -0.323977  0.079216
D -0.274811  0.225988 -0.323977  1.000000  0.469328
E  0.374289 -0.236437  0.079216  

In [18]:
ipl_data = {'Team': ['Riders', 'Riders', 'Devils', 'Devils', 'Kings',
   'Kings', 'Kings', 'Kings', 'Riders', 'Royals', 'Royals', 'Riders'],
   'Rank': [1, 2, 2, 3, 3,4 ,1 ,1,2 , 4,1,2],
   'Year': [2014,2015,2014,2015,2014,2015,2016,2017,2016,2014,2015,2017],
   'Points':[876,789,863,673,741,812,756,788,694,701,804,690]}
df = pd.DataFrame(ipl_data)

print(df)

v = df.groupby('Team')

print("\n\n")
print(v['Points'].agg([np.mean, np.sum, np.median, np.std]))
print("\n\n")
print(v['Rank'].agg([np.mean, np.sum, np.median, np.std]))
print("\n\n")
print(v['Year'].agg([np.std]))

      Team  Rank  Year  Points
0   Riders     1  2014     876
1   Riders     2  2015     789
2   Devils     2  2014     863
3   Devils     3  2015     673
4    Kings     3  2014     741
5    Kings     4  2015     812
6    Kings     1  2016     756
7    Kings     1  2017     788
8   Riders     2  2016     694
9   Royals     4  2014     701
10  Royals     1  2015     804
11  Riders     2  2017     690



          mean   sum  median         std
Team                                    
Devils  768.00  1536   768.0  134.350288
Kings   774.25  3097   772.0   31.899582
Riders  762.25  3049   741.5   88.567771
Royals  752.50  1505   752.5   72.831998



        mean  sum  median       std
Team                               
Devils  2.50    5     2.5  0.707107
Kings   2.25    9     2.0  1.500000
Riders  1.75    7     2.0  0.500000
Royals  2.50    5     2.5  2.121320



             std
Team            
Devils  0.707107
Kings   1.290994
Riders  1.290994
Royals  0.707107


In [8]:
one = pd.DataFrame({
   'Name': ['Alex', 'Amy', 'Allen', 'Alice', 'Ayoung'],
   'subject_id':['sub1','sub2','sub4','sub6','sub5'],
   'Marks_scored':[98,90,87,69,78]},
   index=[1,2,3,4,5])

two = pd.DataFrame({
   'Name': ['Billy', 'Brian', 'Bran', 'Bryce', 'Betty'],
   'subject_id':['sub2','sub4','sub3','sub6','sub5'],
   'Marks_scored':[89,80,79,97,88]},
   index=[1,2,3,4,5])

print(one, "\n\n", two)

print("\n\n", pd.concat([one,two])) # Contact will put a and b togather, also create the different table. 

     Name subject_id  Marks_scored
1    Alex       sub1            98
2     Amy       sub2            90
3   Allen       sub4            87
4   Alice       sub6            69
5  Ayoung       sub5            78 

     Name subject_id  Marks_scored
1  Billy       sub2            89
2  Brian       sub4            80
3   Bran       sub3            79
4  Bryce       sub6            97
5  Betty       sub5            88


      Name subject_id  Marks_scored
1    Alex       sub1            98
2     Amy       sub2            90
3   Allen       sub4            87
4   Alice       sub6            69
5  Ayoung       sub5            78
1   Billy       sub2            89
2   Brian       sub4            80
3    Bran       sub3            79
4   Bryce       sub6            97
5   Betty       sub5            88


In [9]:
one = pd.DataFrame({
   'Name': ['Alex', 'Amy', 'Allen', 'Alice', 'Ayoung'],
   'subject_id':['sub1','sub2','sub4','sub6','sub5'],
   'Marks_scored':[98,90,87,69,78]},
   index=[1,2,3,4,5])

two = pd.DataFrame({
   'Name': ['Billy', 'Brian', 'Bran', 'Bryce', 'Betty'],
   'subject_id':['sub2','sub4','sub3','sub6','sub5'],
   'Marks_scored':[89,80,79,97,88]},
   index=[1,2,3,4,5])

print(one, "\n\n", two)

print("\n\n", one.append(two))# append also put the two tables togather. 

     Name subject_id  Marks_scored
1    Alex       sub1            98
2     Amy       sub2            90
3   Allen       sub4            87
4   Alice       sub6            69
5  Ayoung       sub5            78 

     Name subject_id  Marks_scored
1  Billy       sub2            89
2  Brian       sub4            80
3   Bran       sub3            79
4  Bryce       sub6            97
5  Betty       sub5            88


      Name subject_id  Marks_scored
1    Alex       sub1            98
2     Amy       sub2            90
3   Allen       sub4            87
4   Alice       sub6            69
5  Ayoung       sub5            78
1   Billy       sub2            89
2   Brian       sub4            80
3    Bran       sub3            79
4   Bryce       sub6            97
5   Betty       sub5            88


# 5/3/2019